name: Publish on NPM registry
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Test with Jest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies with pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install NPM dependencies
        run: pnpm install
      - name: Run Jest
        run: pnpm run test
  format:
    name: Check format with Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies with pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install NPM dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm run format:check
